{
  inputs,
  pkgs,
  system,
}:
let
  pre-commit = inputs.git-hooks.lib.${system}.run {
    src = ./.;
    hooks = {
      nixfmt.enable = true;
      statix.enable = true;
      deadnix.enable = true;
    };
    # generated by nixos-generate-config
    excludes = [ "hardware-configuration\\.nix$" ];
  };
in
{
  checks.pre-commit = pre-commit;

  devShells.default = pkgs.mkShell {
    inherit (pre-commit) shellHook;
    packages = pre-commit.enabledPackages;
  };
}
